baseURL = 'https://heuter.xyz/'
languageCode = 'en-US'
title = 'Heuter - Transform Any Content into Powerful Courses'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Blog'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'FAQ'
pageRef = '#faq'
weight = 30

[[menus.main]]
name = "Contact us"
url = "mailto:heuterapp@gmail.com"
weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[params]
  defaultLayout = "single"